- hosts: localhost
  become: true
  tasks:  
  - name: Install ZSH Shell
    apt: name=zsh
  - name: Change Default Shell To ZSH
    shell: chsh -s `which zsh`
  - name: Install ZSH Configuration Framework
    shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  - name: Install ZSH Plugin 'zsh-autosuggestions'
    ansible.builtin.git:
      repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
      dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  - name: Clone .dotfiles Into Bare Repo On HOME Directroy
    ansible.builtin.git:
      bare: yes
      repo: 'https://github.com/adriankuklinski/.dotfiles'
      dest: "$HOME/.cfg"
  - name: Create Git Config Alias
    shell: echo "alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'" >> $HOME/.bashrc
  - name: Set Config .gitignore
    ansible.builtin.lineinfile:
      path: "$HOME/.gitignore"
      state: present
      line: ".cfg"
      create: yes
  - name: Source .bashrc & Checkout Config 
    shell: '/bin/bash -i -c "config checkout && config config --local status.showUntrackedFiles no"'
