name: ansible
region: nyc
services:
  - name: ansible
    github:
      branch: master
      repo: adriankuklinski/ansible
      deploy_on_push: true
    source_dir: /
    dockerfile_path: infrastructure/Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
    routes:
      - path: /
    envs:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ANSIBLE_ApplicationSettings__RequireHttps
        value: "false"
      - key: ANSIBLE_ConnectionStrings__DefaultConnection
        scope: RUN_AND_BUILD_TIME
        value: ${blackhole.DATABASE_URL}
